version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 654654426811.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=654654426811.dkr.ecr.us-east-1.amazonaws.com/catalog-service
  build:
    commands:
      - echo "Building a Docker image.."
      - docker build -t $REPOSITORY_URI:latest --file Dockerfile .
      - echo "Tagging Docker image for ECR.."
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - echo "Pushing Docker image to ECR.."
      - docker push  $REPOSITORY_URI:latest
      - echo "Done."
  post_build:
    commands:
      - echo Writing image definitions file...
      - echo '[{"name":"catalog-service","imageUri":"'$REPOSITORY_URI:latest'"}]' > imagedefinitions.json # Create imagedefinitions.json artifact
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json