version: 0.2
env:
  variables:
    ECR_REPO: 654654426811.dkr.ecr.us-east-1.amazonaws.com/catalog-service
    ECR_REGION: us-east-1
phases:
  build:
    commands:
      - echo "Building a Docker image.."
      - docker build -t catalogservice . --file Dockerfile
      - echo "Tagging Docker image for ECR.."
      - docker tag catalogservice ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - echo "Logging into ECR.."
      - $(aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin 654654426811.dkr.ecr.us-east-1.amazonaws.com)
      - echo "Pushing Docker image to ECR.."
      - docker push ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - echo "Done."